### ISSUE TITLE
 libceres-dev

### ISSUE THREAD

**Issue by millpoint** [YuanxinPan/PPPx_bin#1]
I have installed the libceres-dev, however, the following mistake still occur.

pppx: error while loading shared libraries: libceres.so.2: cannot open shared object file: No such file or director

How can I fix this issue?

**Comment by YuanxinPan** [comment]
Hi! Have you tried to reboot your computer? It would be helpful if you could share a few more details, like your operating system and the version of `libceres-dev` your installed.

**Comment by millpoint** [comment]
my operating system is Ubuntu 18.04.

**Comment by YuanxinPan** [comment]
Hi! It seems that the `libceres-dev` is outdated for Ubuntu 18.04, where the latest version is 1.13.0 instead of 2.x.x:
https://www.ubuntuupdates.org/package/core/bionic/universe/base/libceres-dev

One solution is that you can compile and install the latest version of `ceres-solver` by following the official instructions:
http://ceres-solver.org/installation.html

Note that you might need to uninstall the old 1.13.0 version first. Hope it helps!
PS: You can use the static build `pppx_static` without external dependency (but without the support for FGO).

**Comment by millpoint** [comment]
Thanks a lot. I have installed the ceres-solver 2.2.0 and followed the steps on the official website, however, the mistakes remain. I'm considering updating the operating system from Ubuntu 18.04 to 20.04.

**Comment by YuanxinPan** [comment]
[pppx.zip](https://github.com/user-attachments/files/17702769/pppx.zip)

That is weird... You can try the attached version, which is linked against `libceres-dev 1.x.x`, on your current Ubuntu 18.04. I guess it should work with the libceres-dev you installed with apt.

I'll try to fix this issue in a future release.

**Comment by millpoint** [comment]
Much appreciated. It works now with your attached version. I'm expecting your future release.
